Repository mina-deploy/mina, pull requests merged in 2021-08, with the labels that each got.

#665 Update 3rd_party_plugins.md
  docs/3rd_party_plugins.md
Labels: add to documentation

#677 Ensure branch exists locally and remotely before comparing it
  spec/support/outputs/git_ensure_pushed.txt
  spec/tasks/git_spec.rb
  tasks/mina/git.rb
Labels: bug

#685 Runner tests
  spec/lib/mina/runner/exec_spec.rb
  spec/lib/mina/runner/printer_spec.rb
  spec/lib/mina/runner/system_spec.rb
  spec/spec_helper.rb
Labels: tests

#686 Refactor pretty printer
  .github/workflows/ci.yml
  docs/how_mina_works.md
  lib/mina.rb
  lib/mina/runner/pretty.rb
  mina.gemspec
  spec/lib/mina/runner/pretty_spec.rb
Labels: bug, enhancement

#688 Application tests
  lib/mina/application.rb
  spec/lib/mina/application_spec.rb
Labels: tests

#680 Fix readme issues
  Readme.md
  docs/assets/images/mina.png
Labels: add to documentation

#684 SSH task tests
  spec/support/outputs/ssh.txt
  spec/tasks/default_spec.rb
  tasks/mina/default.rb
Labels: tests

#687 Prevent stdout output in tests
  .rspec
  spec/lib/mina/commands_spec.rb
  spec/lib/mina/configuration_spec.rb
  spec/tasks/default_spec.rb
  spec/tasks/init_spec.rb
Labels: tests

#689 Internal helpers tests
  lib/mina/helpers/internal.rb
  spec/lib/mina/helpers/internal_spec.rb
Labels: tests

#690 Improve test coverage for output helpers
  spec/lib/mina/helpers/output_spec.rb
Labels: tests

#691 Improve test coverage for configuration
  spec/lib/mina/configuration_spec.rb
Labels: tests

#692 Test remaining default tasks
  spec/support/outputs/environment.txt
  spec/support/outputs/ssh_keyscan_domain.txt
  spec/tasks/default_spec.rb
Labels: tests

#693 Version manager tests
  spec/spec_helper.rb
  spec/support/outputs/chruby.txt
  spec/support/outputs/chruby_with_env.txt
  spec/support/outputs/chruby_without_env.txt
  spec/support/outputs/rbenv_load.txt
  spec/support/outputs/rvm_use.txt
  spec/support/outputs/rvm_use_with_env.txt
  spec/support/outputs/rvm_use_without_env.txt
  spec/support/outputs/rvm_wrapper_with_arguments.txt
  spec/support/outputs/rvm_wrapper_without_arguments.txt
  spec/support/outputs/ry.txt
  spec/support/outputs/ry_with_env.txt
  spec/support/outputs/ry_without_env.txt
  spec/support/rake_example_group.rb
  spec/tasks/chruby_spec.rb
  spec/tasks/rbenv_spec.rb
  spec/tasks/ruby_managers_spec.rb
  spec/tasks/rvm_spec.rb
  spec/tasks/ry_spec.rb
  tasks/mina/rvm.rb
Labels: tests

#694 Update tests for Rails tasks
  spec/support/outputs/console.txt
  spec/support/outputs/log.txt
  spec/support/outputs/rails_assets_precompile_force_precompile.txt
  spec/support/outputs/rails_assets_precompile_outside_deploy_block.txt
  spec/support/outputs/rails_assets_precompile_with_diff.txt
  spec/support/outputs/rails_console.txt
  spec/support/outputs/rails_db_migrate.txt
  spec/support/outputs/rails_db_migrate_force_migrate.txt
  spec/support/outputs/rails_db_migrate_outside_deploy_block.txt
  spec/support/outputs/rails_db_migrate_with_diff.txt
  spec/support/outputs/rails_log.txt
  spec/support/outputs/rails_with_arguments.txt
  spec/support/outputs/rails_without_arguments.txt
  spec/support/outputs/rake_with_arguments.txt
  spec/support/outputs/rake_without_arguments.txt
  spec/tasks/rails_spec.rb
Labels: tests

#695 DSL tests
  .gitignore
  Gemfile.lock
  spec/configs/default.rb
  spec/configs/dsl.rb
  spec/lib/mina/application_spec.rb
  spec/lib/mina/dsl_spec.rb
  spec/lib/mina/helpers/internal_spec.rb
  spec/spec_helper.rb
  spec/support/outputs/dsl_deploy.txt
  spec/support/outputs/dsl_in_path.txt
  spec/support/outputs/dsl_local_run.txt
  spec/support/outputs/dsl_on.txt
  spec/support/outputs/dsl_remote_run.txt
  spec/support/outputs/dsl_reset.txt
  spec/support/rake_example_group.rb
  spec/tasks/bundler_spec.rb
  spec/tasks/chruby_spec.rb
  spec/tasks/default_spec.rb
  spec/tasks/deploy_spec.rb
  spec/tasks/git_spec.rb
  spec/tasks/init_spec.rb
  spec/tasks/rails_spec.rb
  spec/tasks/rbenv_spec.rb
  spec/tasks/rvm_spec.rb
  spec/tasks/ry_spec.rb
Labels: tests
